// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fvhkhzpjoeiwsunygkif.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ2aGtoenBqb2Vpd3N1bnlna2lmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQyODEwMDMsImV4cCI6MjA4OTg1NzAwM30.ZFUkpZEZLtQ_FrZWDCDlXfke7iv925-dgh7bd3hf0uk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});